alma-oss/cookie-consent-manager

- .editorconfig
- .github/CODEOWNERS
- .gitignore
- .stylelintrc
Projects settings filed imported from [basic-idea](https://github.com/lmc-eu/cookie-consent-manager/tree/basic-idea) branch by @adamkudrna .
> Default project settings

- .editorconfig
- demo/autoload.html
- demo/bootstrap.html
- package.json
- src/LmcCookieConsentManager.js
- src/languages/cs.js
- src/languages/en.js
Add some plugin defaults, as discussed with product manager.
> Feat: Configure plugin defaults

- .github/workflows/publish.yaml
- .npmrc
- README.md
- bin/ci/npm-auth.sh
- bin/ci/semver.sh
- package.json
> Chore: Introduce publish package pipeline #CCM-8

- .github/workflows/release.yaml
See https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
> Chore: Introduce release action which is triggered manually

- README.md
- package.json
- scripts/readme-replace-version.js
- yarn.lock
Simple regex: https://regex101.com/r/mufpT0/1/
> Chore: Automatically replace package version in readme file to actual

- .npmrc
- .yarnrc
* also some configuration were not respected during publish
> Chore: Use .yarnrc instead of .npmrc because we are using yarn

- .browserslistrc
- README.md
- examples/index.html
- package.json
- postcss.config.js
- src/LmcCookieConsentManager.scss
- src/scss/_cc-theme.scss
- src/scss/_settings.scss
- src/scss/_style.scss
- src/scss/_theme.scss
- src/scss/_tools.scss
- src/scss/index.scss
- yarn.lock
> Feat: Introduce new design connected to Spirit design tokens #CCM-7

- package.json
* @see: https://github.com/lmc-eu/spirit-design-system/commit/076789
> Chore: Fix path change in spirit-design-token@0.4.1

- README.md
Adding references to other parts of readme and unifying codestyle.
> Docs: Minor readme improvements

- README.md
> Docs: Update list of supported languages

- examples/callbacks.html
- examples/configuration.html
- examples/index.html
- examples/theming.html
> Docs: Improve docs design

- examples/theming.html
> Docs: Use switches instead of buttons to demonstrate theming

- README.md
- examples/callbacks.html
- examples/configuration.html
- examples/index.html
- examples/theming.html
- src/scss/_cc-theme.scss
- src/scss/_style.scss
- src/scss/_theme.scss
Removed in favour of `--lmcccm-link-*-text`:
- `--lmcccm-btn-secondary-text`
- `--lmcccm-btn-secondary-hover-text`
- `--lmcccm-btn-secondary-active-text`
New:
- `--lmcccm-btn-font-weight`
> BREAKING CHANGES: Update buttons theming API according to the latest design

- src/LmcCookieConsentManager.js
Once more  :smile: 
:facepalm:
> Fix: Use proper level name stored to dataLayer

- README.md
- bin/ci/semver.sh
- scripts/readme-replace-version.js
Any other ideas what we need to do as part of the stable release?
> Chore: Prepare for stable release

- README.md
- src/scss/_style.scss
- src/scss/_theme.scss
New custom properties:
- `--lmcccm-link-text-decoration`
- `--lmcccm-link-hover-text-decoration`
- `--lmcccm-btn-text-transform`
> Feat: Add more theming options for links and buttons

- package.json
- yarn.lock
Base branch for other PRs using v2.7 (#154, #163, #164).
> Deps: Update and pin to vanilla-cookieconsent 2.7.1 #CCM-51

- README.md
- examples/assets/examples.css
- examples/assets/functions.js
- examples/callbacks.html
- examples/configuration.html
- examples/functions.js
- examples/index.html
- examples/languages.html
- examples/theming.html
To have have a place to easily toggle between supported languages.
> Docs: Add example to show all supported languages

- src/LmcCookieConsentManager.ts
- src/scss/_style.scss
Seems broken now 🤷
So handing this over to @adamkudrna - please commit fixes to this branch, I won't commit to it.
> Refactor: Enable new swap_buttons feature to proper button order by default

- examples/configuration.html
- package.json
- src/LmcCookieConsentManager.ts
- src/consentCollector.ts
- yarn.lock
See [CCM-53](https://jira.int.lmc.cz/browse/CCM-53) .
> Feat: Set cookie expiration when only necessary category accepted

- examples/assets/functions.js
- examples/languages.html
- package.json
- yarn.lock
See https://github.com/orestbida/cookieconsent/releases/tag/v2.8.0 for changes.
> Update dependency vanilla-cookieconsent to 2.8.0 #CCM-58

- renovate.json
* @see https://github.com/lmc-eu/cookie-consent-manager/pull/138
> Chore: Do not exlude stylelint from automated updates anymore

- README.md
- UPGRADE-2.0.md
Should include guide for applying following changes:
> Docs: Add upgrade guide

- src/scss/style/_consent-modal.scss
> Fix unreachable content

- config/jest.config.json
* direcotry with build content
> Test: Fix haste module collision on local machine by ignoring

- package.json
- yarn.lock
> Chore: Add missing peer dependencies

- .github/workflows/build.yaml
- package.json
- yarn.lock
> Chore: Try to build this package also on Node.js v20

- config/jest.config.json
- package.json
- yarn.lock
@crishpeen @adamkudrna Could you please check there isn't some breaking change because of the spirit tokens update? At the first sight it visually looks ok. Thanks!
> Chore(deps): Update dependency @lmc-eu/spirit-design-tokens to v1

- README.md
One more link which I forgot to add to the previous PR :facepalm: .
> Docs: Update another link to orestbida library documentation

- README.md
- examples/configuration.html
- src/LmcCookieConsentManager.ts
- src/__tests__/utils.test.ts
- src/languages/__tests__/__snapshots__/langConfig.test.ts.snap
- src/languages/__tests__/langConfig.test.ts
- src/languages/cs.ts
- src/languages/de.ts
- src/languages/en.ts
- src/languages/hr.ts
- src/languages/hu.ts
- src/languages/pl.ts
- src/languages/ru.ts
- src/languages/sk.ts
- src/languages/sl.ts
- src/languages/uk.ts
- src/types/CookieConsentManager.ts
- src/types/vanilla-cookieconsent.ts
- src/utils.ts
> Feat: Add ability to set cookie table

- package.json
- yarn.lock
* @see: https://sass-lang.com/blog/embedded-sass-is-live/
* more performand
* modern API
> Chore: Switch from `sass` to `sass-embedded`

- yarn.lock
Result of ```yarn upgrade```, to upgrade even all subdependencies.
> Deps: Update all (sub)dependencies

- README.md
- bin/ci/npm-auth.sh
- examples/webpack-with-esm/index.js
- examples/webpack-with-esm/package.json
- examples/webpack-with-typescript/index.ts
- examples/webpack-with-typescript/package.json
- package.json
> BREAKING CHANGE: Change library npm organization to almacareer

- examples/assets/examples.css
- examples/assets/functions.js
- examples/assets/personalization.js
- examples/callbacks.html
- examples/configuration.html
- examples/index.html
- examples/languages.html
- examples/personalization.js
- examples/theming.html
- src/scss/tools/_themes.scss
- src/scss/tools/_typography.scss
**Updated design:**
---
Initial redesigned version:
> Docs: Redesign docs using Spirit Design System

- catalog-info.yaml
And also catalog information for backstage.
> Chore: Replace internal project owner 💨
