alma-oss/cookie-consent-manager

- package.json
There is now no link to the github repo in the sidebar: https://www.npmjs.com/package/@lmc-eu/cookie-consent-manager
> Chore: Add repository URL to make it shown also on npmjs.com

- src/LmcCookieConsentManager.js
There are six scenarios for the callback:
1. `onAccept()` - when any consent is detected (either given right now or already saved previously). This is the same behavior as the native `onAccept()` callback of the library. This one we already have from #17 .
2. `onAcceptOnlyNecessary()` (aka "Reject") - when consent with only necessary cookies is detected (either given right now or already saved previously) .
3. `onAcceptAll()` - when consent with all cookies is detected (either given right now or already saved previously)
4. `onFirstAccept()` - right after any consent is just accepted by the user.
5. `onFirstAcceptOnlyNecessary()` (aka "Reject") - right after only necessary cookies are accepted by the user. May be useful for metrics and removing current cookies.
6. `onFirstAcceptAll()` - …
> Feat: Add callbacks for all onAccept scenarios #CCM-24

- src/LmcCookieConsentManager.js
Instance of the underlying cookie consent library is now returned also from the our constructor.
This may be useful for some edge-cases when you need to access the component in a different workflow then in callback.
```html
<script>
window.addEventListener('load', function () {
window.cc = initLmcCookieConsentManager();
});
</script>
<a href="..." onclick="cc.allowedCategory('analytics') ? console.log('log analytics') : console.log('do not log');">Tracked link</a>
```
> Feat: Return CookieConsent instance from the init function

- README.md
- examples/index.html
- src/LmcCookieConsentManager.js
From talks with some engineers it seems the autodetection will be often disabled (they will just force the language based on current language version of the site). (Sidenote - maybe we should consider whether the autodetection should not be disabled by default...)
Furthermore, I renamed `currentLang` to `defaultLang`, which in my opinion better describes what the value actually means from configuration perspective.
> Configurable language autodetection

- README.md
- src/LmcCookieConsentManager.js
This adds default configuration to enable third-party script management:
```js
page_scripts: true, // Manage third-party scripts loaded using <script>
```
If someone won't use this feature, the overhead in the vanilla library is one call of `var scripts = document.querySelectorAll('script[' + _config.script_selector + ']');` on init. I guess this is acceptable performance tradeoff?
Other option would be leave this as default and add this the configurable parameters. What do you think?
> Feat: Enable management of third-party scripts 

- .github/workflows/publish.yaml
- package.json
- scripts/remove-prepare.js
* `set-script` works from npm v7 and we are on node v14 and npm v6
* we are removing prepare script with husky install because it is
a lifecycle script that is runned before publish
* we are publishing from ./dist directory where are no deps installed
> Chore: Remove prepare script before publishing package

- .editorconfig
- README.md
- examples/callbacks.html
- examples/configuration.html
- examples/functions.js
- examples/index.html
- examples/personalization.js
- examples/theming.html
These are revamped examples - they were prepared for todays presentation, so not everything is as clean as it should. I welcome your suggestions - what examples add, whether the structure should be somehow changed etc.
It is based on bootstrap 5, as I needed something to make it quickly and good looking.
I set GitHub to deploy this branch here: https://lmc-eu.github.io/cookie-consent-manager/examples/
.. so that anyone can see the examples online right now, because the time is pressing us a bit.
~~(Note: the branch is targeted to `test/demo-integration`, which is temporary branch with current main + merged #30. I will switch it to main once #30 is merged).~~
> Docs: Revamp examples #CCM-20

- README.md
- src/LmcCookieConsentManager.js
As discussed, this removes `themeCss` property from the exposed configuration.
We only document the standard way of loading CSS using `<link>` attribute or including it in custom built styles.
> Remove themeCss config property  #CCM-28

- bin/ci/semver.sh
We do not want publish stable version now. But [this commit](https://github.com/lmc-eu/cookie-consent-manager/commit/1df5c0be48156410bc33f2023f6348b8fdfa6338) bumps major version.
> Chore: Skip breaking changes until package is stable

- README.md
- scripts/readme-replace-version.js
Ref. [#CCM-29](https://jira.int.lmc.cz/browse/CCM-29)
Using this users who will use the "recommended" URL to CDN will get bugfixes.
I also think after 1.0.0 we should also drop the "minor" version from the URL. We comply with semver, so this will mean they will get the latest compatible version. But this is up to discussion, as this might possibly be a bit more risky.
> Docs: Do not use patch part in URL to update to bugfix versions automatically

- README.md
- examples/callbacks.html
- examples/configuration.html
- examples/index.html
- examples/theming.html
- src/LmcCookieConsentManager.js
This is the first step of CCM-35. We will require service name to be given on initialization, so that we could submit the consents (CCM-13) in near future, without breaking the API later.
> Require service name to be passed as the first param

- package.json
- src/LmcCookieConsentManager.js
The next part of CCM-35 after #69.
I thought we would not need uuid library... However from what I've read regarding Math.random(), any uuid function based on it would mean high chance of collisions. And since the traffic this would have and necessity to have uuid really unique, this could be problematic.
> Feat: Generate and store consent UUID on accept

- scripts/build.js
* error: Could not resolve "crypto" (use "platform: 'node'" when
building for node)
see
- https://github.com/ai/nanoid/issues/278
- https://github.com/evanw/esbuild/issues/387
- https://github.com/ai/nanoid/commit/b7d116c685204f5c9763b0bec96176b8b428bf3c
> Chore: Fix building when using crypto in nanoid

- .github/workflows/commitlint.yaml
- .github/workflows/lint.yaml
- .github/workflows/test.yaml
What do you think, is this worth it? [The action ](https://github.com/bahmutov/npm-install)caches the yarn cache folder, in invalidates if hash of yarn.lock file changes.
Despite name of the action, it recognizes yarn and run `yarn --frozen-lockfile`, see [log output](https://github.com/lmc-eu/cookie-consent-manager/runs/4290791770?check_suite_focus=true#step:5:12). 
It decreases each yarn `Install dependencies` step by ~10 seconds.
> Chore: Cache yarn dependencies to increase GH Actions jobs speed

- src/scss/_theme.scss
This fix prevents plugin's UI from being rendered with browser's default font (typically Times New Roman) when `Inter` font is not downloadable or installed.
Why `font-family` is not inherited when `Inter` font is not present? When `font-family` is obtained via `var()` function and the font is not available, entire declaration is invalid and — as opposed to direct declaration `font-family: Inter` — the value of `font-family` is reset to browser default.
> On the other hand, if you’re asking why a var() expression doesn’t default to the next best-cascaded value, that’s because by the time the var() expression is evaluated, there are no other values to fall back to, because every other declaration in the cascade has been erased.
https://stackoverflow.com/a/48081355 …
> Fix: Make `font-family` fallback actually work as documented

- README.md
- examples/callbacks.html
- examples/configuration.html
- examples/index.html
- examples/theming.html
- src/LmcCookieConsentManager.js
- src/consentCollector.js
See [#CCM-39](https://jira.int.lmc.cz/browse/CCM-39) .
Will be opt-in first. Once tested, the `enableConsentSubmit` configuration will either by opt-out or completely removed.
Naming suggestions welcomed! (I'm not sure about `dataCollector`, `enableConsentSubmit` and `submitConsent` names...)
> Feat: Submit consent to the API

- src/LmcCookieConsentManager.js
The length of `run()` call is now >50 lines long, so this is hard to read and code smell.
Also, I sometimes want to dump the assembled config, which is now much easier.
(BTW In the future I think it may also be inevitable to move the whole config object assembly to custom method.)
> Refactor: Extract assemble config into variable

- README.md
- examples/callbacks.html
- examples/configuration.html
- examples/index.html
- examples/theming.html
- package.json
- src/LmcCookieConsentManager.js
- yarn.lock
Instead of autodetection based on the browser language, which I don't think will be used by anyone in LMC, we will base the detection on the document root element (`<html lang="...">`), whats is a new option in vanilla cookieconsent 2.7.
> Feat: Autodetect language based on the value of <html lang=...>

- package.json
- src/consentCollector.js
- yarn.lock
The getter was added in the vanilla component (https://github.com/orestbida/cookieconsent/pull/113), allowing us to read the values from the instance.
However, this will now not work properly, because of https://github.com/orestbida/cookieconsent/pull/120 .
So we must wait until this is resolved.
> Feat: Submit to API also current language and cookie expiration #CCM-41

- README.md
- examples/configuration.html
I would add this despite the "auto-TOC" GitHub provides: 
Its nice... But hidden. Better to have the links and quick overview what is in the README right in front of the eyes :eyes: .
> Docs: Add table of contents to readme, grammar fixes

- renovate.json
Tested on https://github.com/literat/literat/pull/18
> Chore(renovate): Set `separateMajorMinor` to false for devDependencies

- examples/assets/examples.css
> Docs: Change text color of success state to improve its contrast with background

- examples/callbacks.html
- examples/configuration.html
- examples/index.html
- examples/theming.html
* missing meta description
* missing `noopener` and `norefferer` for cross-origin links
> Docs(lighthouse): Fix errors reported by Google Lighthouse in examples

- .eslintignore
If you have `build.js` in `examples/webpack*/` and run `yarn lint` in the root directory, it will find in the build.js exactly `1072 problems (924 errors, 148 warnings)` :upside_down_face: .
> Chore: Do not lint build.js in examples

- package.json
- scripts/build.js
* we need to build commonjs module as `browser` to avoid nanoid using
crypto module which is native node.js module
* instead of that we want to use web crypto api
* using `platform:browser` bundler finds right export from nanoid and
use it
* but for this platform bundler did not annotate the commonjs export
so we must do it manually
> Chore: Annotate the CommonJS export names for ESM import in Node

- src/LmcCookieConsentManager.ts
- src/consentCollector.ts
- src/languages/cs.ts
- src/languages/de.ts
- src/languages/en.ts
- src/languages/hu.ts
- src/languages/pl.ts
- src/languages/ru.ts
- src/languages/sk.ts
- src/languages/uk.ts
- src/types/CookieConsentCategory.ts
- src/types/CookieConsentManager.ts
- src/types/index.ts
- src/types/vanilla-cookieconsent.ts
According to [this](https://github.com/orestbida/cookieconsent/issues/144#issuecomment-993448152), "category" should be used instead of "level", which is deprecated name. So lets use "category" everywhere we can. Which is everywhere except low-level-cookie content, which sadly uses the `level` field.
Also in README and in examples we already use category everywhere.
> Refactor: Use category instead of level in type names

- config/jest.config.json
- tsconfig.json
Running tests get unacceptably slow when switching to ts-jest.
On my machine:
- Before: ~1,5 secs
- After: 11 secs :flushed: 
On github actions:
- Before: ~2 secs
- After: ~5 secs
So here are some changes to make jest running faster:
- Do not include examples directory in tsconfig
- Use only one runner (with current number of tests the overhead cost is bigger then benefit). This decreases the time by ~30 % on my 4 CPU machine. Has no measurable impact on github actions, though.
- Use `isolatedModules: true`, [see docs](https://github.com/kulshekhar/ts-jest/blob/main/website/docs/getting-started/options/isolatedModules.md). We lose type-checking in tests, however, as we run `tsc -p` just the step before, its probably redundant. This gets the final time to:
- On my machine: ~2 secs (so <0.5 …
> Chore: Improve jest tests performance

- src/scss/_style.scss
The unwanted spacing was introduced here: https://github.com/orestbida/cookieconsent/blame/350d295ae72ef3ce4358d51435908dabe89f7c2a/src/cookieconsent.css#L248
Before:
After:
> Fix: Fix spacing too big after core library upgrade

- package.json
- yarn.lock
> Chore(changelog): Add missing dependency on conventional-changelog-lmc-github

- .github/CODEOWNERS
This is IMHO better practice for company projects.
Syntax documentation: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#example-of-a-codeowners-file
> Chore: Define codeowners using company e-mail rather than nickname

- examples/languages.html
When selecting a language radio button and reloading the page, at least Firefox remembers the last selection. However as we don't detect the form state on page load and presume the first option is active, the state of the actual language used become inconsistent with the selected input.
This disables the "remember value after reload" feature making the first input always be the active one after page (re)load.
> Docs: Avoid inconsistent states in language selection example

- README.md
- examples/callbacks.html
- examples/configuration.html
- examples/index.html
- examples/languages.html
- examples/theming.html
- examples/webpack-with-esm/index.js
> Scripts with `defer` always execute when the DOM is ready (but before `DOMContentLoaded` event).
— https://javascript.info/script-async-defer#defer
> Docs: Prefer `DOMContentLoaded` over `load` event to render cookie consent modal earlier

- examples/assets/functions.js
- examples/callbacks.html
- examples/index.html
This adds the same list also to callbacks example page. I think its useful to see this on one place when trying to understand the new callbacks in version 2.0.
> Docs: List allowed categories also on callbacks example page

- src/scss/style/_settings-modal.scss
To prevent close button from inheriting secondary button styles on hover:
> Fix: Disconnect settings modal close button from button styles

- src/LmcCookieConsentManager.ts
- src/types/CookieConsentManager.ts
- src/types/vanilla-cookieconsent.ts
* ensure that vanilla cookie consent configuration is type safe
* @see https://github.com/lmc-eu/cookie-consent-manager/pull/218#discussion_r818638417
> Fix: Provide type for vanilla cookie consent options

- yarn.lock
Forcing update of sub-dependency in yarn.lock to fix GitHub Security Warning.
https://github.com/yarnpkg/yarn/issues/4986#issuecomment-395036563
> Deps: Force dependency update of vulnerable minimist

- CHANGELOG.md
> Docs: Fix typo in changelog message

- renovate.json
Based on the declined upgrade of the nanoid to the v4 version which is not supporting CJS, I am telling to Renovate bot not to upgrade the nanoid to v4, until Prace.cz will support ESM.
https://github.com/lmc-eu/cookie-consent-manager/pull/247
> Chore: Update `nanoid` package to v3 branch only

- examples/callbacks.html
- examples/configuration.html
- examples/index.html
- examples/languages.html
- examples/theming.html
* @see: https://www.jsdelivr.com/using-sri-with-dynamic-files
* we are targeting on latest version 5 which means it changes
dynamically and thus integrity attribute hash works until
the next update
* it is recommended to use them only with full version path
> Docs: Remove integrity attributes because of integrity fails

- renovate.json
* there are breaking changes in 2.8.1 and we are waiting to comming
major release
> Chore: Freeze `vanilla-cookieconsent` to 2.8.0 or allow major release

- .github/workflows/build.yaml
Would make sense to test this as well? To make sure the dependencies are resolved in installable tree.
This is currently failing, would be fixed after by #239 .
> Chore: Test build on multiple node versions

- src/scss/theme/_default.scss
- yarn.lock
- **Fix:** Change design token linked to button typography
The design token `body-medium-button` is still present, but deprecated and no longer used by Spirit.
Downstream design systems already don't have this token at all which makes our CSS impossible to compile with them.
- **Deps:** Update Can-I-Use DB used by Browserslist
> Fix button design token

- renovate.json
* @see: https://github.com/lmc-eu/cookie-consent-manager/pull/276
Renovate reads configuration from the main branch, so configuration modifications that were applied in the release/v3 branch were not accepted.
> Chore: Disable update of stylelint-config

- src/LmcCookieConsentManager.ts
There are cases when cookie is not present and `get('data')` returns `undefined`. It is probably caused by strict privacy settings of certain browsers.
See also: https://github.com/orestbida/cookieconsent/blob/v2.8.0/src/cookieconsent.js#L1783
> Fix: Cannot use 'in' operator to search for 'uid' in undefined

- .github/CODEOWNERS
I think there is no need to have these two super ninja developers on each PR of this project ;-)
> Chore: Remove @adamkudrna and @crispeen from codeowners

- src/languages/cs.ts
- src/languages/de.ts
- src/languages/en.ts
- src/languages/hu.ts
- src/languages/pl.ts
- src/languages/ru.ts
- src/languages/sk.ts
- src/languages/uk.ts
- src/types/vanilla-cookieconsent.ts
Backported from https://github.com/orestbida/cookieconsent/blob/v2.9/types/types.d.ts .
> Feat: Extend types to allow cookie tables settings

- README.md
- examples/languages.html
- src/LmcCookieConsentManager.ts
- src/languages/__tests__/__snapshots__/langConfig.test.ts.snap
- src/languages/__tests__/langConfig.test.ts
- src/languages/hr.ts
- src/languages/sl.ts
Still WIP, as we are missing some translations, specifically these: (Czech translation used as a placeholder)
```
and: 'i',
company: 'společnosti',
companies: 'společnostem',
legalName: 'Alma Career a společnostem z její obchodní skupiny',
```
> Add Croatian and Slovenian translations

- README.md
- examples/configuration.html
To keep them working as we still depends on older version 2.9.
> Docs: Update links to orestbida library documentation

- src/LmcCookieConsentManager.ts
- src/__tests__/utils.test.ts
- src/consentCollector.ts
- src/languages/__tests__/__snapshots__/langConfig.test.ts.snap
- src/languages/__tests__/langConfig.test.ts
- src/languages/cs.ts
- src/languages/de.ts
- src/languages/en.ts
- src/languages/hr.ts
- src/languages/hu.ts
- src/languages/pl.ts
- src/languages/ru.ts
- src/languages/sk.ts
- src/languages/sl.ts
- src/languages/uk.ts
- src/types/vanilla-cookieconsent.ts
- src/utils.ts
As discussed in #324, I made at least some DRY simplification of block assembly, so that the language files contains less logic. 
This PR will go before #324 , ie. #324 will be refactored to extend and utilize the `assembleCategoryBlock` method.
What do you think, @literat?
> Refactor block assembly

- package.json
- yarn.lock
The original projects seems not to be maintained anymore and is having some reported vulnerabilities. 
See https://github.com/mysticatea/npm-run-all/issues/256 and https://github.com/mysticatea/npm-run-all/issues/257 .
> Deps: Replace unmaintained npm-run-all

- yarn.lock
Github is reporting security issues in indirect dependencies which won't update.
The update was done manually, as per https://stackoverflow.com/a/60832612/464890
> Deps: Update indirect dependencies with known security vulnerabilities

- package.json
- renovate.json
- yarn.lock
The update was previously blocked by required CJS support, but this was resolved by #356 .
> Deps: Update nanoid to version 5

- examples/configuration.html
- package.json
- src/LmcCookieConsentManager.ts
- yarn.lock
This allows to overwrite multi-level deep config object of the vanilla-cookieconsent.
Used library [Mergican](https://github.com/jhildenbiddle/mergician) is light-weight and does not extend the dependency footprint, as it has no external dependencies.
> Feat: Use deep merge for config overwrites (fixes #385)

- README.md
- examples/callbacks.html
- examples/configuration.html
- examples/index.html
- examples/languages.html
- examples/theming.html
- src/LmcCookieConsentManager.ts
- src/types/CookieConsentManager.ts
To match their new names in vanilla-cookieconsent library.
This causes BC, however, I find this better than having different names from the vanilla library.
> BREAKING CHANGE: Rename callbacks

- package.json
- scripts/readme-replace-version.ts
- yarn.lock
To fix
```
$ ts-node scripts/readme-replace-version.ts
TypeError: Unknown file extension ".ts" for readme-replace-version.ts
at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:183:9)
at defaultGetFormat (node:internal/modules/esm/get_format:209:36)
at defaultLoad (node:internal/modules/esm/load:116:22)
at async ModuleLoader.loadAndTranslate (node:internal/modules/esm/loader:483:32)
at async ModuleJob._link (node:internal/modules/esm/module_job:115:19) {
code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```
> Chore: Update version replace script to ESM

- README.md
- UPGRADE-3.0.md
WIP, but should contain almost everything notable.
> Docs: Add UPGRADE guide for version 3

- package.json
- renovate.json
- src/scss/style/_buttons.scss
- src/scss/style/_preferences-modal.scss
- src/scss/tools/_themes.scss
- yarn.lock
Upgrade our Stylelint config to the latest version.
However, recent Sass deprecation of mixed declarations collides with our Stylelint config order rule. Let's step back to Sass and fix it in our Stylelint config later.
> Deps: Upgrade `@alma-career/stylelint-config`

- UPGRADE-3.0.md
This is newly available since vanilla-cookieconsent 3.1.0.
> Docs: Add language to cookie contents example

- renovate.json
* switch from user defined scheduling and grouping to predefinet presets
I have finalized the migration of `@lmc-eu/renovate-config` package (which is now deprecated) to repository base renovate-config (https://github.com/alma-oss/renovate-config), which is prefered solution from the Renovate itself.
So, now the repository configuration can be smaller.
> Chore: Use alma's sharable preset for renovate
